name: Artifacts

on: push # all kind of actions

jobs:
  aratifacts:
    name: working on artifacts
    runs-on: ubuntu-latest
    steps:
    # The below script generates, uploads and downloads three files.
      - shell: bash 
        run: |
          expr 1 + 1 > /tmp/output.log 
          mkdir -p path/to/dir-1
          mkdir -p path/to/dir-2
          mkdir -p path/to/dir-3
          echo "Lorem ipsum dolor sit amet" > path/to/dir-1/file-A.txt
          echo "Hello world from file B" > path/to/dir-2/file-B.txt
          echo "compress a large file with GZip. The @actions/artifact package uses GZip to upload files. This text should have a compression ratio greater than 100% so it should get uploaded using GZip" > path/to/dir-3/gzip.txt

      - name: Upload file output.log 
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file # optional.Can give any name. If not given will sow as 'artifact'. this is the name shows in github.  We can download it manually
          path: /tmp/output.log # should be same as created file path
          retention-days: 1 # optional. default value is 90 days. max value for public repo:90 days, max value for private repo:400 days

      # - name: Upload file file-A.txt
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: file A # this is the name shows in github. Can give any name. We can download it manually
      #     path: path/to/dir-1/file-A.txt # should be same as created file path

      - name: 'Upload Gzip folder'
        uses: actions/upload-artifact@v3
        with:
          name: 'GZip-Artifact'
          path: path/to/dir-3/

      - name: 'Upload multiple files together'
        uses: actions/upload-artifact@v3
        with:
          name: 'Multiple artifacts'
          path: |
            path/to/dir-1/file-A.txt
            path/to/dir-2/*
            !path/to/dir-3/*.txt

      - name: Download file output.log to default path  # download default path /home/runner/work/CypressWeb_v10_CICD/CypressWeb_v10_CICD
        uses: actions/download-artifact@v3
        with:
          name: output-log-file # file name should be same as we given in upload
          path: some/new/path # path is optional. If didnt mention it will downlaod default path. If mentioned, deafult/some/new/path
      
      - name: Download file output.log to new path
        uses: actions/download-artifact@v3
        with:
          name: output-log-file # file name should be same as we given in upload
          path: ~/some/path/with/a/tilde   # download path /home/runner/some/path/with/a/tilde

      - name: Download all Artifacts # if we dont mention name then it will download all uploaded artifacts
        uses: actions/download-artifact@v3
        with:
          path: some/other/path
      
      - name: Download all Artifacts- using wild cards in the path
        uses: actions/download-artifact@v3
        with:
          path: some/**/path # wild cards in the path. wildcard is actually useful while uploading
      

     # The below script takes screenshot and uploads for cypress test execution
      - name: Checkout
        uses: actions/checkout@v3
      - name: Take screenshot
        if: failure()
        run: |
          ./bin/makeScreenshot /tmp/screen.jpg

      - name: Upload screenshot
        uses: actions/upload-artifact@master # upload our screen shot to GitHub. We can download it from github (dropdown shown at upper right corner)
        # if: failure() # these steps will only run if some previous steps have failed.
        # if: success() && github.ref == 'refs/heads/master' # If it is master branch
        if: failure()
        with:
          name: screen.jpg
          path: /tmp/screen.jpg

      - name: Running cypress scripts
        uses: actions/checkout@v3
      - run: npm ci # same as npm install
      - run: npx cypress run 

    # The below script uploads screenshot and videos from cypress suite
      - name: Upload screenshot
        uses: actions/upload-artifact@master
        if: failure()
        with:
            name: screenshots
            path: cypress/screenshots
        # there might be no screenshots created when:
        # - there are no test failures
        # so only upload screenshots if previous step has failed

    # video should always be generated
      - name: Upload videos
        uses: actions/upload-artifact@master
        if: failure() # success()
        with:
            name: videos
            path: cypress/videos
